kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: micro-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80      # ingress-nginx listens on 80
        hostPort: 8080         # accessible on localhost:8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
  - role: worker
  - role: worker