apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80        # The port the service exposes
      targetPort: 8000 # The port your FastAPI container is listening on
